/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// TypeScript 6 added a strict check for side-effect imports (TS2882), which
// now requires an ambient declaration for CSS side-effect imports like
// `import '@/global.css'` that previously typechecked without one.
declare module '*.css';